### ISSUE TITLE
Constant values undefined

### ISSUE THREAD

**Issue by TonyGravagno** [ademarre/binary-to-text-php#4]
Constants **TRUE** and **FALSE** are used in Base2n.php, without being undefined. Please change these to **true** and **false**, lower case, no quotes.

https://github.com/ademarre/binary-to-text-php/blob/5d98d17be16d65e03851654a717293a4317bb947/Base2n.php#L51

This might be trivial, but perhaps not. This plugin is used in some secure code and these details could affect results in this code or when used from other code.

**Comment by TonyGravagno** [comment]
**Closed issue**
According to the [PHP manual](https://www.php.net/manual/en/language.types.boolean.php) :

> To specify a boolean literal, use the constants TRUE or FALSE. Both are case-insensitive.

But a linter flags this because according to [PSR-2](https://www.php-fig.org/psr/psr-2/#25-keywords-and-truefalsenull) : 

> PHP keywords MUST be in lower case.
> The PHP constants true, false, and null MUST be in lower case. 

So this is purely a matter of consistency and style, not core functionality.

My bad - oops :face_with_head_bandage:

**Comment by ademarre** [comment]
Thank you. Yes, `TRUE` or `true` in PHP is a matter of style. When I originally wrote this, I preferred uppercase because that was the style used in the official PHP docs. I have since switched sides to keep up with modern conventions like PSR-2, and eventually that may make its way into this library.

**Comment by TonyGravagno** [comment]
Should we re-open this as a reminder for a later time when you make that decision?

**Comment by ademarre** [comment]
I don't think it's necessary to re-open. Thanks.
