### ISSUE TITLE
No releases show up in packagist.

### ISSUE THREAD

**Issue by samuelwilliams** [ademarre/binary-to-text-php#5]
G'Day,

No releases show up in Packagist, so the only version constraint I can use in composer is "dev-master". Would you be able to fix up the constraints?

Cheers,

Sam

**Comment by ademarre** [comment]
Yes, I should have versioned this properly ages ago. I'll get on that.

Thanks for the request.

**Comment by ademarre** [comment]
The current release is v3.0.0 and it is now listed in Packagist. @samuelwilliams, thank you for reporting the issue.
